### ISSUE TITLE
UsersController

### ISSUE THREAD

**Issue by Technopathic** [cbradley3/srl-backend#1]
Hi Charlie,

You did well on the UsersController with a few exceptions.
Line 25:
`'name' => 'required',`
Should be:
`'username' => 'required',`
The same applies to your update function's rules.

On the update function, you may also want to do the user existence check as well, just you've already done in the store function. See Lines 37 to 42 of your code.

On Line 53:
`public function update($id)`
Should be:
`public function update($id, Request $request)`

Since the update function is also receiving data from the Front-End. 

Keep it up, Charlie.

**Comment by cbradley3** [comment]
Those changes have been made and pushed. Please review. Thanks.
