### ISSUE TITLE
Controllers

### ISSUE THREAD

**Issue by Technopathic** [cbradley3/srl-backend#2]
Hi Charlie,

In your CategoriesController, be sure that your Store function returns a response to let the user know the category was successfully saved. 
In your OrdersController, let's not make the "comment" input a required rule. Not everyone will want to make comments, Line 27 and 55. 
Please finish the RolesController.

Keep it up, Charlie.

**Comment by Technopathic** [comment]
Hi Charlie,
Looking at the OrdersController, in the Store Function:
I don't believe there should be a name input at all. 
totalPrice should also not be required either as the backend will do the math on that. 
The same applies to the Update Function. 

Your RolesController has an input for "username", but it should just be "name" in the Store and Update functions. 

In the CategoriesController,
Line 23 and Line 34 need to match correctly.
`$request->input('category');` the "category" part needs to be the same as the "name" in `'name' => 'required'`
So essentially Line 23 should be:
`'category' =>'required'`
OR
Line 34 should be:
`$category->name = $request->input('name');`

Lines 43 and 55 in the Update function also require the same attention.

**Comment by cbradley3** [comment]
Code has been updated. Please recheck. Thanks.
