### ISSUE TITLE
Controllers 

### ISSUE THREAD

**Issue by Technopathic** [cbradley3/srl-backend#3]
Hi Charlie,

In your CategoriesController's index function, you should allow all users to be able to view all categories. Like when you're shopping on Amazon, you can browse by categories. 

In the OrdersController, for the update function, you should allow only the admin or the authenticated user to update orders, just like how you did with the destroy function. The show function should also only allow the admin and the authenticated user to see their individual orders. 

In your ProductsController's index function, All users should be able to browse products, so you shouldn't be checking for admin in the index function here. The same with the Show function. 

Also, keep in mind that any function where you used "Auth", you must also have a __construct function inside that controller which has the jwt.auth middleware and filters that function through jwt.auth.

Keep it up, Charlie.

**Comment by cbradley3** [comment]
Those changes have been made. Please review. Thanks.
